### ISSUE TITLE
UDP networking support

### ISSUE THREAD

**Issue by bkolobara** [lunatic-solutions/lunatic-rs#17]
The lunatic vm exposes host functions for working with UDP. They just need to be wrapped into higher level rust types, similar to TCP.

**Comment by pinkforest** [comment]
I could work on a PR for this

**Comment by bkolobara** [comment]
Awesome!

**Comment by pinkforest** [comment]
net::UdpSocket - foundation, bind, local_addr - #29

**Comment by pinkforest** [comment]
I think I've blumbed everything thats out there available.

**Comment by bkolobara** [comment]
I will close this, for the multicast stuff we can open additional issues once someone needs it.
