### ISSUE TITLE
Add method `block_until_shutdown` to `Supervisor`

### ISSUE THREAD

**Issue by bkolobara** [lunatic-solutions/lunatic-rs#18]
It will just block until the `Supervisor` is shut down.

When it's called the process will send a self-reference to the supervisor and wait on an answer forever. The supervisor will in case of shutdown **or failure** send a message to the process to unblock it.

**Comment by MarkintoshZ** [comment]
I think I can take a poke at this. 

Just for clarification, the process that wants to be blocked until shutdown will send a message to the supervisor with the self-reference, which the method `block_until_shutdown` will then be called, correct?

**Comment by MarkintoshZ** [comment]
So how would we block the process? Do we keep track over the process ids on the `Supervisor` struct and then send messages to those processes when `terminate` is being called?

**Comment by bkolobara** [comment]
The process is automatically "blocked" while waiting on a message. It would send a message to the supervisor and then forever just wait by calling `receive()`.
