### ISSUE TITLE
Make `Process` Public

### ISSUE THREAD

**Issue by MarkintoshZ** [lunatic-solutions/lunatic-rs#49]
`Process` should be public, right? There is currently no way to have an `AbstractProcess` receive a reference to a Mailbox process to send messages to.

**Comment by bkolobara** [comment]
`Process` is already public: https://github.com/lunatic-solutions/lunatic-rs/blob/main/src/function/process.rs#L113

**Comment by MarkintoshZ** [comment]
Oh right, never mind.
