### ISSUE TITLE
Allow specifying configuration & tag when spawning from WasmModule

### ISSUE THREAD

**Issue by HurricanKai** [lunatic-solutions/lunatic-rs#76]
It'd be useful to allow specifying the usual options for processes spawned from `WasmModule`.
Config especially to limit resources, for me especially heap size, but the other options are likely handy in other scenarios.
I haven't looked deeper into failure recovery & using Tags, but it seems like usually the way to handle failures is attaching a Tag to subprocesses and handling the `MailboxResult::LinkDied` messages. This isn't possible with processes spawned from WasmModule.

Having a quick look at the implementation this seems like a minor change. Looks like the only difference between WasmModule::spawn* and Process::spawn* is that WasmModules don't use `host::spawn` but `host::api::process::spawn`, effectively making WasmModules only spawn on the local node, but it's still possible to pass in all the parameters, just like `host::spawn` would do in a non-distributed environment.

**Comment by HurricanKai** [comment]
I've now actually noticed that it's not actually possible to spawn a process from a module, as the relevant function always passes `-1` as config id, which crashes lunatic.

**Comment by bkolobara** [comment]
I have extended the API to include spawn functions that can take tags and configs. I have also published a `0.11.2` version that includes this changes. They need more testing though, so let me know if everything works!

**Comment by HurricanKai** [comment]
This works well for me. Thank you!
