### ISSUE TITLE
Improve `#[lunatic::main]` & `#[lunatic::test]` macro error reporting

### ISSUE THREAD

**Issue by bkolobara** [lunatic-solutions/lunatic-rs#9]
If there is an error (syntax, signature mismatch, ...) inside of the main function wrapped by the `#[lunatic::main]` macro, the compiler & `rust-analyzer` will mark the whole file as invalid and report:
```
`main` function not found in crate `x`
consider adding a `main` function to `src/main.rs`
```

This happens because the macro returns before generating the `main` function. And it becomes impossible to figure out what the actual error is. Would love to have the actual error reported here, something like:

```
Function `main` is missing an argument
consider adding it `fn main(mailbox: Mailbox<T>)`
```

I would suggest just check out what other crates do in this case (e.g. `#[tokio::main]`) and copy their approach of error handling.

**Comment by justjosias** [comment]
Has this been resolved? Whenever there's a syntax error now, it appears to display the correct error, in line with tokio and actix.

**Comment by bkolobara** [comment]
Hi @justjosias, thank you for looking into this.

The correct error is reported, but there is still the issue that if the macro can't parse the block it will not emit the the `main` function and the whole file is market by rust-analyser as invalid:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/593393/166417352-33965dc9-2f66-425d-9973-31edc5c78ac0.png">

> In this example only an additional comma is the issue at the end of the main block.

I think the problem is that we in https://github.com/lunatic-solutions/rust-lib/blob/main/lunatic-macros/src/lib.rs#L9 use the expression `let input = syn::parse_macro_input!(item as syn::ItemFn);` that will fail to compile and not emit back the content of `main`.

I think we could do something like tokio https://docs.rs/tokio-macros/1.7.0/src/tokio_macros/entry.rs.html#387
```
let input: syn::ItemFn = match syn::parse(item.clone()) {
    Ok(it) => it,
    Err(e) => return token_stream_with_error(item, e),
};
```
to just return back the same token stream (including main) if we fail to compile it. I assume this could fix it.
