### ISSUE TITLE
Async Request Handlers

### ISSUE THREAD

**Issue by drue** [lunatic-solutions/lunatic-rs#93]
Feature Request

It would be nice if abstract process request handlers could return some simple deferred/promise/future type while retaining the synchronous API for clients.

The use case I have in mind is a DB connection pool similar to Erlang's Poolboy.  A pool manager launches a set of workers which each own a DB connection.  Clients check out a worker ref from the manager then send the worker requests until they return the worker to the supervisor with a check in message.

When there are no available workers the manager must return something so it doesn't block its mailbox servicing loop.  Instead of returning `Option` or `Result` and making the client retry it would be preferable for the manager to return a deferred type which it could stash in a queue.  Later, when a worker becomes available, the deferred is resolved with the newly available worker reference.   This triggers a callback which was set on the deferred by the outer abstract process handler when the initial request handler returned.  The callback just extracts the return value from the deferred type and sends a normal response with the real return type.

While the server API is asynchronous the client API remains synchronous.  The macro would parse and extract the real return type so the clients wouldn't see the deferred/promise/future return type.

Another possibility is having the deferred response created by the outer handler and passed in as an argument to the user supplied handler instead of being created and returned there.  Then it can be passed to sub-processes with the callback already set, allowing abstract processes to easily use sub-processes to service requests.

example:

```rust
struct Pool{
    workers: Vec<ProcessRef<Worker>>,
    waiters: Vec<DeferredResponse<ProcessRef<Worker>>>,
};

#[abstract_process]
impl Pool {
    #[init]
    fn init(_: ProcessRef<Self>, num_workers: u32) -> Self {
       let workers = start_workers(num_workers);
       let waiters = Vec::new();
       Self(workers, waiters);
    }

    #[handle_request_async]
    fn check_out(&mut self) -> DeferredResponse<ProcessRef<Worker>> {
       let deferred = DeferredResponse::new();
       self.workers.pop() match {
         None => self.waiters.push(deferred),
         Some(worker) => deferred.set_value(worker),
       }
       deferred
    }

    #[handle_message]
    fn check_in(&mut self, worker: ProcessRef<Worker>) {
       self.waiters.pop() match {
           None => self.workers.push(worker),
           Some(deferred) => deferred.set_value(worker),
       }
    }
}

#[lunatic::main]
fn main(_: Mailbox<()>) {
    let pool = lookup("DBPool");
    let worker:ProcessRef<Worker> = pool.check_out();

    worker.begin();
    worker.query("drop table STUDENTS;");
    worker.commit();

    pool.check_in(worker);
}
```

**Comment by bkolobara** [comment]
Thanks @drue for putting the work in and explaining the use-case. I saw similar use-cases come up in discord questions and think we should provide an abstraction for this. I'm currently also restructuring some of the `AbstractProcess` stuff and will see what the best way of doing this would be.

I also think that this API should allow for specifying a timeout if the `deferred.set_value()` function is never called.
